credentials:
  usernames:
    jay:
      email: jay.patel@infosenseglobal.com
      name: Jay Patel
      password: '$2b$12$O97Jfaq/vmK8Zh.7EuyIrOtdO.EPzyRDrGeAr48sMZpsD1xmtgdX2'
cookie:
  expiry_days: 0
  key: 'K8s Control Panel Cookie Key'
  name: 'K8s Control Panel Cookie'
preauthorized:
  emails:
  - jay.patel@infosenseglobal.com